import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Button } from "../ui/button";
import { ArrowRight, Play, Sparkles, Code, Terminal, Zap } from "lucide-react";
export const HeroSection = () => {
    return (_jsxs("section", { className: "relative min-h-screen  text-white flex items-center justify-center overflow-hidden pt-20", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-hero" }), _jsx("div", { className: "absolute inset-0 bg-grid-pattern opacity-30" }), _jsx("div", { className: "absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl floating" }), _jsx("div", { className: "absolute bottom-1/4 right-1/4 w-80 h-80 bg-neon-cyan/15 rounded-full blur-3xl floating", style: { animationDelay: "-3s" } }), _jsx("div", { className: "absolute top-1/2 right-1/3 w-64 h-64 bg-neon-pink/10 rounded-full blur-3xl floating", style: { animationDelay: "-1.5s" } }), _jsxs("div", { className: "container mx-auto px-4 lg:px-8 relative z-10", children: [_jsxs("div", { className: "max-w-5xl mx-auto text-center", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, className: "inline-flex items-center gap-2 px-4 py-2 rounded-full glass-panel mb-8", children: [_jsx(Sparkles, { className: "w-4 h-4 text-primary animate-ping" }), _jsx("span", { className: "text-sm font-medium text-muted-foreground", children: "Trusted by 50,000+ developers worldwide" })] }), _jsxs(motion.h1, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.1 }, className: "text-4xl sm:text-5xl md:text-6xl lg:text-7xl  font-bold leading-tight mb-6", children: ["Master Coding with", " ", _jsx("span", { className: "gradient-text", children: "Code Mitra" })] }), _jsx(motion.p, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.2 }, className: "text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed", children: "Transform your coding journey with industry-ready courses. Learn Python, JavaScript, Full-Stack Development, and more with hands-on projects and expert guidance." }), _jsxs(motion.div, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.3 }, className: "flex flex-col sm:flex-row items-center justify-center gap-4 mb-16", children: [_jsx(Link, { to: "/courses", children: _jsxs(Button, { variant: "premium", size: "xl", className: "group", children: ["Start Learning Free", _jsx(ArrowRight, { className: "w-5 h-5 group-hover:translate-x-1 transition-transform" })] }) }), _jsx(Link, { to: "/about", children: _jsxs(Button, { variant: "glass", size: "xl", className: "group", children: [_jsx(Play, { className: "w-5 h-5" }), "Watch Demo"] }) })] }), _jsx(motion.div, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.4 }, className: "grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-8", children: [
                                    { value: "50K+", label: "Active Learners" },
                                    { value: "100+", label: "Expert Courses" },
                                    { value: "95%", label: "Completion Rate" },
                                    { value: "4.9", label: "Student Rating" },
                                ].map((stat, index) => (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.4, delay: 0.5 + index * 0.1 }, className: "glass-panel p-4 md:p-6", children: [_jsx("div", { className: "text-2xl md:text-3xl font-bold gradient-text mb-1", children: stat.value }), _jsx("div", { className: "text-sm text-muted-foreground", children: stat.label })] }, stat.label))) })] }), _jsx(motion.div, { initial: { opacity: 0, x: -50 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.8, delay: 0.6 }, className: "hidden lg:block absolute left-8 top-1/2 -translate-y-1/2", children: _jsx("div", { className: "glass-panel p-4 floating", style: { animationDelay: "-2s" }, children: _jsx(Code, { className: "w-8 h-8 text-primary" }) }) }), _jsx(motion.div, { initial: { opacity: 0, x: 50 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.8, delay: 0.7 }, className: "hidden lg:block absolute right-8 top-1/3", children: _jsx("div", { className: "glass-panel p-4 floating", style: { animationDelay: "-1s" }, children: _jsx(Terminal, { className: "w-8 h-8 text-neon-cyan" }) }) }), _jsx(motion.div, { initial: { opacity: 0, y: 50 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.8 }, className: "hidden lg:block absolute right-16 bottom-1/4", children: _jsx("div", { className: "glass-panel p-4 floating", style: { animationDelay: "-0.5s" }, children: _jsx(Zap, { className: "w-8 h-8 text-neon-pink" }) }) })] }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 h-32 bg-linear-to-t from-background to-transparent" })] }));
};
